apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactjs
  template:
    metadata:
      labels:
        app: reactjs
    spec:
      containers:
      - name: reactjs
        image: prashanth63/reactjs:mmt
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: reactjs-service
spec:
  selector:
    app: reactjs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer