apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactJs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactJs
  template:
    metadata:
      labels:
        app: reactJs
    spec:
      containers:
      - name: reactJs
        image: mugu:123
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: reactJs-service
spec:
  selector:
    app: reactJs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer